Test 06 - mergeTB - merging into the end
Read in TB from 'simple-1.txt' into tb1
> linesTB(tb1);
7
> dumpTB(tb1, false);
line 01
line 02
line 03
line 04
line 05
line 06
line 07
Read in TB from 'simple-2.txt' into tb2
> linesTB(tb2);
5
> dumpTB(tb2, false);
line one
line two
line three
line four
line five
> mergeTB(tb1, 8, tb2);
> linesTB(tb1);
12
> dumpTB(tb1, false);
line 01
line 02
line 03
line 04
line 05
line 06
line 07
line one
line two
line three
line four
line five
> releaseTB(tb1);
